---
distro_package_command: zypper
distro_specific_deps:
  - gcc
  - gdk-pixbuf-loader-rsvg
  - git
  - librsvg2
  - libxslt-devel
  - make
  - openssl-devel
  - python-bugzilla
  - python-curses
  - python-dateutil
  - python-dmidecode
  - python-ethtool
  - python-iniparse
  - python-m2crypto
  - python-nose
  - python-pip
  - rpm-build

distro_specific_subman_build_deps:
  - dbus-1-glib-devel
  - desktop-file-utils
  - distribution-release
  - gconf2-devel
  - gettext
  - gtk3-devel
  - intltool
  - libnotify-devel
  - libzypp
  - lsb-release
  - openssl-devel
  - python-devel
  - python-setuptools
  - python-six
  - rpm-python
  - scrollkeeper
  - update-desktop-files

libexec_path: /usr/lib
