---
subman_checkout_dir: .
subman_setup_hacking_environment: false
subman_add_vagrant_candlepin_to_hosts: false
distro_package_command: yum
distro_specific_deps:
  - dbus-x11
  - gcc
  - git
  - koji
  - librsvg2
  - libselinux-python
  - libxslt-devel
  - m2crypto
  - make
  - python-dmidecode
  - python-ethtool
  - python-pip
  - tito
  - xorg-x11-server-Xvfb
  - yum-utils
