name: libdnf

on:
  pull_request:
  workflow_dispatch:

jobs:
  libdnf:
    name: "libdnf"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "CentOS Stream 9"
            image: "quay.io/centos/centos:stream9"

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Enable CRB repository"
        if: ${{ matrix.name == 'CentOS Stream 9' }}
        run: |
          dnf --setopt install_weak_deps=False install -y dnf-plugins-core
          dnf config-manager --enable crb

      - name: "Install packages"
        run: |
          dnf --setopt install_weak_deps=False install -y \
            cmake gcc glib2-devel libdnf-devel json-c-devel

      - name: "Run libdnf plugin test"
        run: |
          cd './src/plugins/libdnf'
          mkdir build && cd build
          cmake ../ -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          make
          CTEST_OUTPUT_ON_FAILURE=1 make test
