name: libdnf

on:
  pull_request:
  workflow_dispatch:

jobs:
  libdnf:
    name: "libdnf"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "CentOS Stream 8"
            image: "quay.io/centos/centos:stream8"

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Use CentOS Vault"
        run: |
          sed -i 's|#baseurl=http://mirror|baseurl=http://vault|' /etc/yum.repos.d/CentOS-Stream-*.repo

      - name: "Enable PowerTools repository"
        run: |
          dnf --setopt install_weak_deps=False install -y dnf-plugins-core
          dnf config-manager --enable powertools

      - name: "Install packages"
        run: |
          dnf --setopt install_weak_deps=False install -y \
            cmake gcc glib2-devel libdnf-devel json-c-devel

      - name: "Run libdnf plugin test"
        run: |
          cd './src/dnf-plugins/product-id'
          mkdir build && cd build
          cmake ../ -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          make
          CTEST_OUTPUT_ON_FAILURE=1 make test
