name: stylish

on:
  pull_request:
  workflow_dispatch:

jobs:
  stylish:
    name: "black & flake8 & rpmlint"
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - name: Base setup
      run: |
        dnf --setopt install_weak_deps=False install -y \
            git-core \
            python3-flake8 \
            python3-pip \
            rpmlint

    - uses: actions/checkout@v6

    - uses: psf/black@stable
      with:
        version: "24.3.0"

    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1

    - name: Run flake8
      run: |
        flake8

    - name: Run rpmlint
      run: |
        rpmlint subscription-manager.spec
